package com.example.homebarincompose.ui.theme

import androidx.compose.ui.graphics.Color

val Purple200 = Color(0xFFBB86FC)
val Purple500 = Color(0xFF6200EE)
val Purple700 = Color(0xFF3700B3)
val Teal200 = Color(0xFF03DAC5)

internal object HomeBarColors {

    val light_primary = Color(0xFFCCE1E4)
    val light_onPrimary = Color(0xFFFFFFFF)
    val light_primaryContainer = Color(0xFF97F0FF)
    val light_onPrimaryContainer = Color(0xFF638C92)
    val light_secondary = Color(0xFF99AD80)
    val light_onSecondary = Color(0xFFFFFFFF)
    val light_secondaryContainer = Color((0xFFFFDBC9))
    val light_onSecondaryContainer = Color(0xFF789979)
    val light_tertiary = Color(0xFF7C9C7D)
    val light_onTertiary = Color(0xFFFFFFFF)
    val light_tertiaryContainer = Color(0xFFFFD9E2)
    val light_onTertiaryContainer = Color(0xFF6B816C)
    val light_error = Color(0xFFB60D1A)
    val light_errorContainer = Color(0xFFFFDAD6)
    val light_onError = Color(0xFFFFFFFF)
    val light_onErrorContainer = Color(0xFF6B130D)
    val light_background = Color(0xFFFFFBFF)
    val light_onBackground = Color(0xFFAD8890)
    val light_surface = Color(0xFFFFFBFF)
    val light_onSurface = Color(0xFFA9C0AA)
    val light_surfaceVariant = Color(0xFFDBE4E6)
    val light_onSurfaceVariant = Color(0xFF3F484A)
    val light_outline = Color(0xFF6F797A)
    val light_inverseOnSurface = Color(0xFFFFECED)
    val light_inverseSurface = Color(0xFFC1D1C2)
    val light_inversePrimary = Color(0xFF5B815D)
    val light_shadow = Color(0xFF000000)
    val light_surfaceTint = Color(0xFF006874)
    val light_outlineVariant = Color(0xFFBFC8CA)
    val light_scrim = Color(0xFF000000)


    val dark_primary = Color(0xFF3A372F)
    val dark_onPrimary = Color(0xFF352424)
    val dark_primaryContainer = Color(0xFF3B4434)
    val dark_onPrimaryContainer = Color(0xFF364425)
    val dark_secondary = Color(0xFF1A1B10)
    val dark_onSecondary = Color(0xFF13E7D2)
    val dark_secondaryContainer = Color(0xFF656B4F)
    val dark_onSecondaryContainer = Color(0xFF1a1e00)
    val dark_tertiary = Color(0xFF131A12)
    val dark_onTertiary = Color(0xFF311A24)
    val dark_tertiaryContainer = Color(0xFF7B2949)
    val dark_onTertiaryContainer = Color(0xFFFFD9E2)
    val dark_error = Color(0xFFFFB4AB)
    val dark_errorContainer = Color(0xFFDFA5A9)
    val dark_onError = Color(0xFF690005)
    val dark_onErrorContainer = Color(0xFFFFDAD6)
    val dark_background = Color(0xFF070707)
    val dark_onBackground = Color(0xFFC9A6A6)
    val dark_surface = Color(0xFF1B1F1B)
    val dark_onSurface = Color(0xFF809181)
    val dark_surfaceVariant = Color(0xFF3F484A)
    val dark_onSurfaceVariant = Color(0xFFBFC8CA)
    val dark_outline = Color(0xFF899294)
    val dark_inverseOnSurface = Color(0xFF40000E)
    val dark_inverseSurface = Color(0xFFFFDADB)
    val dark_inversePrimary = Color(0xFF006874)
    val dark_shadow = Color(0xFF000000)
    val dark_surfaceTint = Color(0xFF4FD8EB)
    val dark_outlineVariant = Color(0xFF3F484A)
    val dark_scrim = Color(0xFF000000)


    val seed = Color(0xFFF6F6F6)
    val CustomColor1 = Color(0xFFFFF4EF)
    val light_CustomColor1 = Color(0xFF954A04)
    val light_onCustomColor1 = Color(0xFFFFFFFF)
    val light_CustomColor1Container = Color(0xFFFFDCC6)
    val light_onCustomColor1Container = Color(0xFF311300)
    val dark_CustomColor1 = Color(0xFFFFB786)
    val dark_onCustomColor1 = Color(0xFF502400)
    val dark_CustomColor1Container = Color(0xFF723600)
    val dark_onCustomColor1Container = Color(0xFFFFDCC6)
}
   /* val seed = Color(0xFFF6F6F6)
    val CustomColor1 = Color(0xFFFFFFFF)
    val CustomColor2 = Color(0xFFC24492)
    val light_CustomColor1 = Color(0xFF006874)
    val light_onCustomColor1 = Color(0xFFFFFFFF)
    val light_CustomColor1Container = Color(0xFF97F0FF)
    val light_onCustomColor1Container = Color(0xFF001F24)
    val dark_CustomColor1 = Color(0xFF4FD8EB)
    val dark_onCustomColor1 = Color(0xFF00363D)
    val dark_CustomColor1Container = Color(0xFF004F58)
    val dark_onCustomColor1Container = Color(0xFF97F0FF)
    val light_CustomColor2 = Color(0xFFA62C7A)
    val light_onCustomColor2 = Color(0xFFFFFFFF)
    val light_CustomColor2Container = Color(0xFFFFD8E9)
    val light_onCustomColor2Container = Color(0xFF3C0029)
    val dark_CustomColor2 = Color(0xFFFFAFD8)
    val dark_onCustomColor2 = Color(0xFF610045)
    val dark_CustomColor2Container = Color(0xFF870B61)
    val dark_onCustomColor2Container = Color(0xFFFFD8E9)

}*/